### ISSUE TITLE
Windows CMD scripts do not work/use a makefile instead of CMD/Shell scripts

### ISSUE THREAD

**Issue by Yersho** [cxd4/rsp#28] opened 2020-09-28 20:57 UTC
I tried running the CMD script make_w64.cmd however it did not build both rsp.dll or rspdebug.dll. The text file linked at the end of my issue is the CMD output I got after running the script.
Also because I didn't want to make 2 issues I would like to suggest using a makefile instead of scripts. That way you can select whether you build 32bit or 64bit on Windows via MSYS2-MinGW32/64 or build the Linux .so files if you are on Linux.

CMD output from running make_w64.cmd:
[cxd4rsp build output.txt](https://github.com/cxd4/rsp/files/5295001/cxd4rsp.build.output.txt)

**Comment by cxd4** [comment] 2020-10-14 23:56
Try changing this line.

```shell
ld --shared -e DllMain -o "%obj%\rspdebug.dll" -L%lib64% %OBJ_LIST% -lmsvcrt
```

`-e DllMain` was an argument I had used to lower the entry point into not depending on extra CRT startup linkages.  If you are having errors like that linking the plugin, I would bet that me hacking the DLL size down like that could be the culprit on a newer version of MinGW.

If you remove that and change `ld` to `gcc` (to include more implicit linkage instructions), it should work, but I could not test or change it myself since I don't have access to a Windows system anymore.

**Comment by Yersho** [comment] 2020-10-15 01:11
I changed the line to:
`gcc --shared -o "%obj%\rspdebug.dll" -L%lib64% %OBJ_LIST% -lmsvcrt`
and it still did not successfully output the rsp.dll and rspdebug.dll files.

CMD output from running the modified make_w64.cmd:
[cxd4rsp build output2.txt](https://github.com/cxd4/rsp/files/5381862/cxd4rsp.build.output2.txt)

**Comment by cxd4** [comment] 2020-10-16 04:17
`CPR_specifier` is merely an enumerated list of constants if you look at where the errors are referencing.
The symbolic linkage to references is different on Windows, so again I cannot test or reproduce what you say.

Try either moving it from `su.h` to the top of `su.c`, or prefix `typedef` (<space>) before the `enum`.

**Closed** 2020-10-18 02:50 UTC

**Comment by Yersho** [comment] 2020-10-18 02:57
Oh this got closed with the fix. Going to confirm the plugin does build now and I tested it on the 64 bit version of Project 64 and there seemed to be no problems. Noticed you left `-e DllMain` in the script however when I tested it just now it didn't give me any errors so it should be fine. Sorry I didn't reply to this before hand just never got the time.

**Comment by cxd4** [comment] 2020-10-18 03:12
Indeed.  The `-e DllMain` should be a supported standard for setting the entry point to a WINAPI DllMain function rather than the C run-time library's default main entry point for MinGW DLLs on Windows.  I was hoping it would eliminate all the added function dependencies outside of libmsvcrt, but with recent versions of MinGW apparently they've changed things since the last time I built it myself on Windows, based on the fix by @ExtremeDude2.

But thank you for confirming that it builds and runs okay now on the 64-bit version of a N64 emulator.  I don't know if Project64 ever got their recompiler ported to 64-bit (particularly for their RSP as well), but if so then good.

**Comment by Yersho** [comment] 2020-10-18 03:23
They have a 64bit version on their Github https://github.com/project64/project64
Idk how finished it is but I used that since I couldn't get make_w64.cmd to build a plugin compatible with the 32bit version (although I blame myself for just not knowing how the script works). I'll get MinGW to use make_w32.cmd and confirm if the script builds a Project 64 32bit compatible build.

**Comment by Yersho** [comment] 2020-10-18 03:42
Ok make_w32.cmd successfully builds a working plugin for Project 64 32bit. Issue is confirmed resolved.

**Comment by RokkumanX** [comment] 2020-10-28 12:03
@Yersho 

Would you mind sharing your compiled cxd4 32-bit plugin here? I have tried getting a hold of a fresh copy for a long time now.

Thanks in advance!

**Comment by RokkumanX** [comment] 2020-10-29 07:09
I don't understand why my innocent comment and request for a binary was removed, @cxd4 I don't even know why you are hosting your project on GitHub if you don't want any publicity let alone requests from people.

You removing my comment just for requesting @Yersho for a binary really offended me and frankly I don't want anything to do with mafia projects like yours anymore.

I'm sure you will remove this comment to, and if you do you'll sure have proven that this project is more fitted as a Archived project.

**Comment by cxd4** [comment] 2020-10-29 12:59
Not an appropriate place to be asking for file-sharing.

Any issues with building the plugin, please create a GitHub issue.  Thanks!
