### ISSUE TITLE
make script issue

### ISSUE THREAD

**Issue by bryanperris** [cxd4/rsp#30] opened 2021-05-23 05:24 UTC
https://github.com/cxd4/rsp/blob/855a26f53497d5f51273ceadbc4998541c551495/make.sh#L19

It should just be a single equal sign, the double equals causes this error in the shell
`./make.sh: 19: [: x86_64: unexpected operator`

**Comment by cxd4** [comment] 2021-05-26 05:08
[GNU Bash conditional syntax](https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html)
>When the ‘==’ and ‘!=’ operators are used, the string to the right of the operator is considered a pattern and matched according to the rules described below in Pattern Matching, as if the extglob shell option were enabled. The ‘=’ operator is identical to ‘==’.

[conditional expressions in bash](https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html)
>string1 == string2
string1 = string2
>>True if the strings are equal. When used with the [[ command, this performs pattern matching as described above (see Conditional Constructs).
>>‘=’ should be used with the test command for POSIX conformance.

I have never seen the `=` variant in shell script checks before.  The latter of the two sources seems to suggest it may be the superior alternative in the case of test commands (i.e., conditional suspensions delimited between `[` and `]` before returning to the calling shell).

**Comment by cxd4** [comment] 2021-05-26 05:10
@bryanperris what version shell are you using?  If you are on Windows, was this the result of running `./make.sh` in Windows 10's UNIX shell script support from within Git Bash?

Unless it is a non-bash shell (I am not sure if that's possible for this file; I'm not an expert on various shells.), `bash --version` should identify the full version of GNU bash you are using.  So what is the output of that?  e.g.,
```
bash-5.1$ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-slackware-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by bryanperris** [comment] 2021-05-26 12:13
Ubuntu 21.04
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

The odd thing now that it works, also zsh is the shell I use, but I added `#!/bin/bash` and thought it still had the same issue

**Comment by cxd4** [comment] 2021-05-27 05:59
I guess I'm just uncertain if it can be concluded that the non-POSIX-compliant `==` necessarily was what caused the syntax error at the time you used to get it, among other borrowed syntactical deviations I was using outside of that.

I will agree that I have found more than enough evidence that `=` is more universally compatible than `==`, so there can be no harm from eliminating that possibility in the (most likely) event that it was the cause or could have been.  I am not very good with bash so almost certainly had to have copied that convention years ago off of somewhere; aside from C sentimentality there is no advantage to keeping it the way it is.  So this ticket will be closed as soon as the syntax is corrected for better compatibility.

>Also the script should provide the shebang, especially if you prefer the bash style comparison.

I'm not sure what the "shebang" is in reference to.  If there is another good idea missing in the implementation that is outside the issue here I would be happy to look at a separate ticket.

**Closed** 2021-05-27 06:41 UTC

**Comment by bryanperris** [comment] 2021-05-27 14:49
shebang is `#!/bin/bash` at the very first line of the file, its good practice to have it in every script that way the shell figures out exactly what interpreter to run for the script.  Python files can include `#!/bin/python` to run script automatically in the python environment else the shell may try to parse the python script as bash or sh.

https://en.wikipedia.org/wiki/Shebang_(Unix)

I am not an bash expert either, I always have to google things for bash.

**Comment by bryanperris** [comment] 2021-05-29 23:36
What about using cmake over scripts?  You won't then need platform specific scripts as cmake works under windows, msys2, Mac and linux

**Comment by bryanperris** [comment] 2021-05-29 23:42
Cmake can be setup to let the user to specify settings they want to enable through -D args

**Comment by cxd4** [comment] 2021-05-30 06:48
My experience thus far has been pretty positive with projects depending on CMake to build them.  It's usually quite the time-saver for larger projects with lots of dependencies my distribution doesn't officially track out-of-the-box, so while I am needing to build a complex package on my distro I can get detailed errors of what I'm missing when a project requires CMake.

I also like that it's more high-level than the plain old GNU make is.  I will typically just use low-level shell scripts because a) I haven't learned how to use CMake and not sure I have time to learn it and b) most of my projects are very simple and low on dependency requirements (if any exist), so there is less for CMake to have to configure.  It's mostly just me being lazy; I wouldn't see anything wrong with keeping a contributed CMake build alternative to the existing low-level script I can maintain.  However, if problems do arise with my shell script solution being dependent on a particular flavor shell (such as bash), I do also see them as opportunities to learn how to eliminate those and practice making more agnostic shell scripts.

**Comment by cxd4** [comment] 2021-05-30 06:55
>Cmake can be setup to let the user to specify settings they want to enable through -D args

I actually ended up having to learn that just recently.  I was building OpenMW (which was more of a pain for me because Slackware has no automatic dependency resolution (which I am content with for the most part)), and the cutting-edge branch required a version of `bullet` library that needed to be build with double-precision.  So I had to edit the SlackBuild to append `-DBT_USE_DOUBLE_PRECISION` to `CMAKE_C_FLAGS` since none of the pre-built packages for that library would let me compile OpenMW.

To be fair, though, that particular feature is also supported in plain shell scripts.  You would just instead pass `-DBT_USE_DOUBLE_PRECISION` as an operand to GCC, so I think the syntax is the same for both CMake and old-fashioned Unix shell scripts in that regard.

**Comment by bryanperris** [comment] 2021-05-30 15:50
You can also use environment vars `CFLAGS` and `CXXFLAGS` as well.  

Are you directly adding `-DBT_USE_DOUBLE_PRECISION` to `CMAKE_C_FLAGS`? Remember the -D defined variables are only visible inside of Cmake and not the underlying toolchain with the exception of some variables that auto translate to C/CXX flags.

Maybe you just need: `export CLFAGS=" BT_USE_DOUBLE_PRECISION " before running the `make`

Are you part of the Discord64 server?

**Comment by bryanperris** [comment] 2021-05-30 16:01
https://pybullet.org/Bullet/phpBB3/viewtopic.php?p=17624&sid=f5190231c49c8eee2ac77cac0a338d90#p17624

**Comment by bryanperris** [comment] 2021-05-30 19:44
I quickly wrote up a CMakeLists file for the library, and verified it compiles and executes.  I haven't tested it under Windows or msys2.

https://github.com/bryanperris/rsp/blob/master/CMakeLists.txt

**Comment by cxd4** [comment] 2021-05-31 08:43
It had worked out fine the way I did it.  The SlackBuild is basically just a shell script that references a tarred/compressed source archive for compiling and linking the package.  (And I just really did not feel like unzipping, editing the CMake lists, and re-zipping with an updated macro.)  So yes, in so many words, I added the `-DBT_USE_DOUBLE_PRECISION` to `SLKCFLAGS` (which more-or-less directly equates to the `CMAKE_C_FLAGS` vector passed by the SlackBuild/SLK CFLAGS).
